### ISSUE TITLE
Subclasses of org.jpmml.evaluator.Computable throw EvaluationException if result is null

### ISSUE THREAD

**Issue by chr1st1anh** [jpmml/jpmml-evaluator#9] opened 2015-05-14 09:57 UTC
Why do subclasses of Computable like InstanceClassificationMap throw an EvaluationException if the getResult is called and result is null (e.g: https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/InstanceClassificationMap.java)? Wouldn't it be more correct to leave the interpretation of an expected/unexpected "null" result up to the caller?

**Comment by vruusmann** [comment] 2015-05-14 10:40
There are two types of predictive models based on their origin:
1. **Supervised learning**. The predictive model returns a scalar value. For example, regression models, classification models.
2. **Unsupervised learning**. The predictive model returns a "queriable object" that can respond to different kinds of user queries with scalar values. For example, clustering models, association and sequence rules.

So, you question basically relates to the representation of those "queriable objects". The current decision is to throw an EvaluationException, which should communicate to to the application user that she must be more specific about what kind of result aspect is she interested in.

For example, class `org.jpmml.evaluator.Association` simply hold state about fired antecedent and decedent rules. It does not have a default result value that could be returned in the `Computable#getResult()` method. However, it can respond to three kinds of user queries: 1) "calculate recommendations", 2) "calculate exclusive recommendations" and 3) "calculate associations".

Sure, it would be helpful to have a high level API to distinguish between supervised and unsupervised models. It is a bit more complex than simply applying finctional marker interfaces like `org.jpmml.evaluator.Supervised` and `org.jpmml.evaluator.Unsupervised` to evaluator classes, because they need to be implemented conditionally, based on the contents of any given PMML document. Maybe, a indicator propery like `Evaluator#isSupervised()` would be more appropriate. I'm trying to come up with a proper solution in the 1.2.X development branch, which is set to launch in the summer.

Currently, you can distinguish between the two by looking up the name of the target field using `Evaluator#getTargetField()` and checking if its is non-null (supervised learning) or null (supervised). But beware, because it is (at least, theoretically) possible to obtain a null name for a supervised model as well. Some advice for dealing with such "phantom target fields" is provided in the Javadoc of the method `org.jpmml.manager.Consumer#getTargetField()`.

Again, I intend to write a detailed technical article about model data schemas very soon.

**Comment by chr1st1anh** [comment] 2015-05-14 11:25
Thanks, the target field is a good workaround. The Association case is more complex... in general if the exception would provide some context about the reason for the evaluation to fail, I might have been able to figure out the supervised/unsupervised difference. E.g. unsupervised/supervised for InstanceClassficationMap, for Association it could reference getRuleValues, ...

**Comment by vruusmann** [comment] 2015-05-14 11:35
A `null` reference is reserved for a missing computation result. A missing result is a different concept than an unavailable/undefined value. For example, if you evaluate a `RegressionModel` element or a `GeneralRegressionModel` element with an empty arguments map then, according to the PMML specification, the result is a missing value that is returned to you as a `null` reference.

So, we need a special-purpose mechanism for informing application developers that they need need to initialize the workflow differently for supervised and unsupervised models. This information must be available statically, well before the first data record is submitted for evaluation.

**Comment by chr1st1anh** [comment] 2015-05-14 11:42
Agreed, I was wondering why else the null result could happen...

**Comment by vruusmann** [comment] 2015-05-14 11:47
The association rules model is functionally different from all other model types, because you need to perform the aggregation of data records in your application code before and after invoking the `Evaluator#evaluate(Map)` method.

I would recommend you to check the type of the evaluator class using the `instanceof` operator and handle association rules separately from the rest:
```
Evaluator evaluator = pmmlManager.getModelManager(ModelEvaluatorFactory.getInstance());
if(evaluator instanceof AssociationModelEvaluator){
  // Initialize association rules-specific workflow that aggregates input data records and de-aggregates output records
} else {
  // Initialize generic workflow
}
```

However, if you know in advance that you will never have to deal with association rules model (which is typically the case), then you can only implement the generic workflow part. If this assumption gets violated (eg. someone unintentionally uploads an association rules model) and `Association#getResult()` is invoked, then the application will throw an EvaluationException that saves the day.

**Comment by chr1st1anh** [comment] 2015-05-14 11:53
This is a good tip and I'll use it for the integration.

**Comment by vruusmann** [comment] 2019-01-08 21:09
Closing this issue, as I believe that it has been thoroughly fixed over the past 3.5 years.

**Closed by vruusmann** 2019-01-08 21:09 UTC

**Comment by AayushSameerShah** [comment] 2022-11-07 07:23
I am trying to run the Association model in my workflow referring to this example: [Example Link](https://github.com/jpmml/jpmml-example/blob/master/src/main/java/org/jpmml/example/AssociationModelEvaluationExample.java)

I am using jpmml-evaluator version `1.6.3` and it seems like the **EvaluatorUtil** class no longer have a `.prepare` method as shown in the example: [Example link 54th line](https://github.com/jpmml/jpmml-example/blob/8ec9e53fa0c4d648769b25dd299814ffae91f7af/src/main/java/org/jpmml/example/AssociationModelEvaluationExample.java#L54)

My code goes like:
```java
// Just getting the PMML object
String path = "ShoppingAssocRules.xml";

File initialFile = new File(path);
InputStream targetStream = new FileInputStream(initialFile);
PMML pmml = PMMLUtil.unmarshal(targetStream);
System.out.println("[PMML LOADED]");

AssociationModelEvaluator associationModelEvaluator = new AssociationModelEvaluator(pmml);
List<InputField> activeFields = associationModelEvaluator.getActiveFields();

// Make sure that all user supplied item values conform to the data schema
FieldValue activeValue = EvaluatorUtil.prepare(associationModelEvaluator, activeField, "Bakery, Milk");

...
```

My IDE shows an error under EvaluatorUtil.<u>prepare</u>(...).
____
I would really appreciate your help Villu sir.
Thank you.

**Comment by vruusmann** [comment] 2022-11-07 07:31
@AayushSameerShah Please open a new issue!

The fact that the `EvaluatorUtil#prepare(...)` utility methoid has been removed is not related to this issue in any way (ie. potential NPE). Where did you get the idea to post it here?

Do I really have to lock every resolved issue?
