### ISSUE TITLE
PMML namespace URI http://www.dmg.org/PMML-4_4 is not supported

### ISSUE THREAD

**Issue by appleyuchi** [jpmml/jpmml-evaluator#196] opened 2020-07-13 15:28 UTC
my pom.xml
is:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>machine_learning</groupId>
    <artifactId>machine_learning</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <springVersion>4.1.1.RELEASE</springVersion>
        <slf4j.version>1.6.6</slf4j.version>
        <log4j.version>1.2.12</log4j.version>
        <shiro.version>1.2.3</shiro.version>
        <mysql.version>5.1.6</mysql.version>
        <mybatis.version>3.4.5</mybatis.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>

    <dependency>
        <groupId>org.jpmml</groupId>
        <artifactId>pmml-evaluator</artifactId>
        <version>1.4.1</version>
    </dependency>

    <dependency>
        <groupId>org.jpmml</groupId>
        <artifactId>pmml-evaluator-extension</artifactId>
        <version>1.4.1</version>

    </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${springVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${springVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${springVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${springVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${springVersion}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <version>${springVersion}</version>
        </dependency>

        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-evaluator</artifactId>
            <version>1.4.13</version>
        </dependency>

        <dependency>
            <groupId>org.jpmml</groupId>
            <artifactId>pmml-evaluator-extension</artifactId>
            <version>1.4.13</version>
        </dependency>

    </dependencies>

</project>

Then I run the code(run the pmml file generated by sklearn):
https://paste.ubuntu.com/p/tjdyRP2khs/

I get the error:

Exception in thread "main" java.lang.IllegalArgumentException: PMML namespace URI http://www.dmg.org/PMML-4_4 is not supported

could anyone tell me what happened?
and how to solve above Exception?
Thanks for your help.

**Comment by vruusmann** [comment] 2020-07-13 18:09
Closing as exact duplicate of https://github.com/jpmml/jpmml-evaluator/issues/195

You're depending on JPMML-Evaluator version 1.4.1, which was released in March 2018.

If you're interested in evaluating PMML schema version 4.4. documents (released in late 2019), then you'd need to upgrade to JPMML-Evaluator 1.5.X.

**Closed by vruusmann** 2020-07-13 18:09 UTC

**Comment by appleyuchi** [comment] 2020-07-14 02:50
after change 1.4.1 to 1.5.1 
the same error remains.

**Comment by vruusmann** [comment] 2020-07-14 04:16
> after change 1.4.1 to 1.5.1
> the same error remains.

Bullshit - The JPMML-Evaluator development branch 1.5.X is specifically about adding PMML schema version 4.4 support.

Check your classpath. You appear to having more than one JPMML-Evaluator dependency declaration there (1.4.1 and 1.4.13).

**Comment by appleyuchi** [comment] 2020-07-14 07:45
Thanks for your replies.
Evaluator evaluator = modelEvaluatorFactory.newModelEvaluator(pmml)
could you tell me how to modify it?
Thanks for your help


Wrong 2nd argument type. Found: 'java.lang.String', required: 'org.dmg.pmml.Model' less... 
Inspection info:
newModelEvaluator
(PMML,
org.dmg.pmml.Model)
in ModelEvaluatorFactory cannot be applied
to
(PMML,
java.lang.String)

**Comment by justforword** [comment] 2021-01-26 06:41
hi，Maybe it can help you
change your xxx.pmml like this:
<PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.4">
to
<PMML xmlns="http://www.dmg.org/PMML-4_3" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.3">

**Comment by dlutleixin** [comment] 2021-04-29 07:57
> hi，Maybe it can help you
> change your xxx.pmml like this:
> `<PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.4">`
> to
> `<PMML xmlns="http://www.dmg.org/PMML-4_3" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.3">`

@justforword solve problem, amazing
