### ISSUE TITLE
[jpmml-evalutaor]“Element OutputField is not valid” when I try to load the PMML file(xgboost4j 0.90)

### ISSUE THREAD

**Issue by harumaj** [jpmml/jpmml-evaluator#168] opened 2019-08-23 03:23 UTC
Hello, Author!

First, in spark + scala, I use PMML Builder to generate xgboost PMML documents.(xgboost 4j: 0.90) .So I imported this dependency when I created it.  https://github.com/jpmml/jpmml-sparkml-xgboost 
It succeeded.

But when I try to load PMM documents again using jpmml-evaluator method, I get an error "Element OutputField is not valid".
![图片](https://user-images.githubusercontent.com/54426731/63564451-ade96b00-c597-11e9-801c-2ba718c7344d.png)

When I checked the PMML document, I found four lines in the output field.
![图片](https://user-images.githubusercontent.com/54426731/63564188-ac6b7300-c596-11e9-8e76-a170e9603e42.png)
I guess because probablity (0) and probablity (1) have two data types (float and double), jpmml-evaluator cannot recognize output field. After I tried to delete two rows of data type as float, jpmml-evaluator was able to successfully parse PMML documents and make predictions.

I don't know why such errors occur when generating or reading PMML documents.
Or maybe could you tell me how to solve this error? I guess the reason for this error is the inconsistency of data type between jpmml-xgboost and PMMLB Builder for output field. The former is double, and the latter is float, which leads to errors. I wonder if my guess is correct.

Looking forward to your reply!

**Comment by vruusmann** [comment] 2019-08-23 04:22
Closing as exact duplicate of https://github.com/jpmml/jpmml-sparkml-xgboost/issues/13

**Closed by vruusmann** 2019-08-23 04:22 UTC
