### ISSUE TITLE
Performing Transformations without Evaluation

### ISSUE THREAD

**Issue by Geoiv** [jpmml/jpmml-evaluator#138] opened 2018-12-20 18:53 UTC
JPMML Devs,

Your library continues to be incredibly useful to me, and I am curious if there is a way to accomplish a particular functionality with it. I am working in a very specific environment where translation of transformers is requiring a a great deal of manual work, due to the structure of the transformers - they were not designed with translation to PMML in mind, to say the least. As a result, it would be incredibly helpful for testing successful tanslation to be able to send CSV data to `pmml-evaluator-executable-1.4-SNAPSHOT.jar` as shown in your example code and have the transformed data output to a CSV, without an evaluation/estimation being applied. Is this at all possible with this project/JAR file?

As always, I am very appreciative of any advice you may have for me, and look forward to hearing from you.

**Comment by vruusmann** [comment] 2018-12-20 19:47
Closing this as functional duplicate of #96 

You might want to check out pull request #116. To make it work as a command-line application, you need to modify class `org.jpmml.evaluator.EvaluationExample`, and replace the use(s) of `ModelEvaluator` with `Transformer`.

**Closed by vruusmann** 2018-12-20 19:47 UTC
