### ISSUE TITLE
Got an exception while loading PMML file generated by jpmml-sparkml

### ISSUE THREAD

**Issue by BurrowsWang** [jpmml/jpmml-evaluator#222] opened 2021-04-28 02:45 UTC
Environment:
```shell
java=1.8.0
spark=2.4.7
jpmml-sparkml=1.5.12
jpmml-evaluator=1.4.x, 1.5.x
```
Here is the PMML file I generated with jpmml-sparkml-1.5.12:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.4">
    <Header>
        <Application name="JPMML-SparkML" version="1.5.12"/>
        <Timestamp>2021-04-27T12:37:19Z</Timestamp>
    </Header>
    <DataDictionary>
        <DataField name="x0" optype="continuous" dataType="double"/>
    </DataDictionary>
    <TransformationDictionary>
        <DerivedField name="bin_x0" optype="categorical" dataType="integer">
            <Discretize field="x0" dataType="integer">
                <DiscretizeBin binValue="0">
                    <Interval closure="closedOpen" rightMargin="-0.616452"/>
                </DiscretizeBin>
                <DiscretizeBin binValue="1">
                    <Interval closure="closedOpen" leftMargin="-0.616452" rightMargin="0.253137"/>
                </DiscretizeBin>
                <DiscretizeBin binValue="2">
                    <Interval closure="closedClosed" leftMargin="0.253137"/>
                </DiscretizeBin>
            </Discretize>
        </DerivedField>
    </TransformationDictionary>
</PMML>
```
yet when I load this PMML file with jpmml-evaluator, the following Exception raised:
```java
org.jpmml.evaluator.MissingElementException: Required element PMML/<Model>@isScorable=true is not defined
```

**Comment by siyouhe666** [comment] 2021-04-28 07:38
+1

**Comment by vruusmann** [comment] 2021-04-28 20:44
Closing as an exact duplicate of https://github.com/jpmml/jpmml-sparkml/issues/112

**Closed by vruusmann** 2021-04-28 20:44 UTC
