### ISSUE TITLE
why create jar file create error

### ISSUE THREAD

**Issue by mojtaba-roohi** [jpmml/jpmml-evaluator#269] opened 2023-11-03 15:19 UTC
hello 
i write code and run on local without bug 
after run my code on docker create error

       return new LoadingModelEvaluatorBuilder()
                .load(resource.getInputStream())
                .transform(new TranspilerTransformer(new FileTranspiler("org.test.LightGBMPredictor",
                       new File("LightGBM_predictor.pmml.jar")))).build();

2023-10-31T14:49:38.204557298+03:30 /org/test/LightGBMPredictor.java:10: error: package jakarta.xml.bind does not exist
2023-10-31T14:49:38.233118300+03:30 /org/test/LightGBMPredictor.java:11: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.243074403+03:30 /org/test/LightGBMPredictor.java:12: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.250293244+03:30 /org/test/LightGBMPredictor.java:13: error: package org.dmg.pmml does not exist
/org/test/LightGBMPredictor.java:14: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.268143632+03:30 /org/test/LightGBMPredictor.java:15: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.276233974+03:30 /org/test/LightGBMPredictor.java:16: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.284206232+03:30 /org/test/LightGBMPredictor.java:17: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.291971750+03:30 /org/test/LightGBMPredictor.java:18: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.299700811+03:30 /org/test/LightGBMPredictor.java:19: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.308187628+03:30 /org/test/LightGBMPredictor.java:20: error: package org.dmg.pmml does not exist
2023-10-31T14:49:38.315883647+03:30 /org/test/LightGBMPredictor.java:21: error: package org.dmg.pmml does not exist

**Comment by vruusmann** [comment] 2023-11-03 15:37
Closing as exact duplicate of https://github.com/jpmml/jpmml-transpiler/issues/26

> i write code and run on local without bug
> after run my code on docker create error

When your application runs in environment A, and does not run in environment B, then it means that there is something wrong with your application. Hint: please learn how to set up your application classpath correctly.

**Closed by vruusmann** 2023-11-03 15:37 UTC
