### ISSUE TITLE
Introduce Release Notes for each version

### ISSUE THREAD

**Issue by masosky** [jpmml/jpmml-evaluator#102] opened 2018-02-26 15:27 UTC
Hi,
First, I would like to say that your job is amazing and these libraries are really useful.
Could you please provide release notes for each version, at least a list of changes would be very bice.

For example, if you click this link, you cannot find any notes:
https://github.com/jpmml/jpmml-evaluator/releases/tag/1.4.0

Thank you very much.

Xavi

**Comment by vruusmann** [comment] 2018-02-26 15:43
Duplicate of #1

**Closed by vruusmann** 2018-02-26 15:43 UTC
