### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by benman1** [jpmml/jpmml-evaluator#11] opened 2015-10-05 15:33 UTC
I do realise this might sound like a stupid question, but I am not used to java nor mvn. I've spent already more than an hour trying to install the evaluator. I've first tried mvn get with the central repository, then git cloning and mvn build, both haven't got me nowhere. Please advise, highly appreciated. 
1. approach: 
   
   > mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.jpmml:pmml-evaluator:1.2.5:jar -DoutputDirectory=.
   > I've tried a lot of variants of this command searching around and looking over tutorials. But I am still not sure, where to go from here. 
   > When I try
   > java -jar target/pmml-evaluator-1.2.5-sources.jar
   > it tells me about a missing manifest file. I've tried including this in the pom file provided in the central repository including the option -DpomFile=pom.xml, but it's complaining about the execution ids. 
2. approach: 
   
   > git clone https://github.com/jpmml/jpmml-evaluator
   > cd jpmml-evaluator/
   > mvn build pom.xml

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jpmml:pmml-evaluator:jar:1.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.jpmml:jpmml-evaluator:1.2-SNAPSHOT (/Users/<>/target/jpmml-evaluator/pom.xml) points at org.jpmml:pmml-evaluator instead of org.sonatype.oss:oss-parent, please verify your project structure @ org.jpmml:jpmml-evaluator:1.2-SNAPSHOT, /Users/benjamin/target/jpmml-evaluator/pom.xml, line 5, column 10
...
[much more of this]
...
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] JPMML-Evaluator
[INFO] JPMML evaluator
[INFO] JPMML evaluator example
[INFO] JPMML KNIME integration tests
[INFO] JPMML RapidMiner integration tests
[INFO] JPMML R/Rattle integration tests
[INFO] JPMML evaluator code coverage
[INFO] JPMML extension
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JPMML-Evaluator 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JPMML-Evaluator .................................... FAILURE [  0.388 s]
[INFO] JPMML evaluator .................................... SKIPPED
[INFO] JPMML evaluator example ............................ SKIPPED
[INFO] JPMML KNIME integration tests ...................... SKIPPED
[INFO] JPMML RapidMiner integration tests ................. SKIPPED
[INFO] JPMML R/Rattle integration tests ................... SKIPPED
[INFO] JPMML evaluator code coverage ...................... SKIPPED
[INFO] JPMML extension .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.158 s
[INFO] Finished at: 2015-10-05T16:24:08+01:00
[INFO] Final Memory: 5M/65M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "pom.xml". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
...

**Comment by vruusmann** [comment] 2015-10-05 17:21
The installation instructions that are given in `README.md` assume that the user is familiar with the Apache Maven way of project management. The reason is that the JPMML-Evaluator library depends on a number of 3rd party libraries, and it would be rather difficult to manage all this complexity otherwise.

You are pretty close to building the project with approach 2. Simply change the third command to Apache Maven's default `mvn clean install`. The build produces the same set of JAR files that can be downloaded from the Maven Central repository. If you are looking for a single uber-JAR type of thing that you could simply drop to your own project's `lib` directory, then `pmml-evaluator-example/target/example-1.2-SNAPSHOT.jar` is the closest to it.

However, I would strongly recommend you to invest some time into Apache Maven. You can use the example application POM file `pmml-evaluator-example/pom.xml` as a starting point for your own project.

I will think about enhancing the `README.md` file with installation instructions for Apache Ant and other project management tools. Will close this issue when ready.

**Comment by benman1** [comment] 2015-10-05 20:17
Thank you, Villu, it worked! I cd into jpmml-evaluator/pmml-evaluator-example, change the pom.xml to include the main method as a manifest attribute, and compile using mvn clean install. Cheers!

**Comment by phsieh** [comment] 2016-05-11 23:43
Thanks for writing this library.  Also, thanks for posting this question.  I think there might be quite a few people who are unfamiliar with maven who find this helpful (i.e. me).

**Comment by vruusmann** [comment] 2016-05-12 07:00
@phsieh You should also check out the [JPMML-Evaluator-Bootstrap] (https://github.com/jpmml/jpmml-evaluator-bootstrap) project, which provides a sample Apache Maven configuration for getting started with a new PMML-powered application.

Installing Apache Maven is a one-time effort (downloading binary distribution archive, unzipping it, and adding its `bin` directory to your system path). But it will save you tremendous amounts of effort afterwards, because it provides an easy and reproducible way of building Java software from source (eg. will be applicable to building pretty much any Java software that you can find in GitHub).

**Comment by xliu-L1** [comment] 2017-10-13 15:00
I tried mvn clean install and I've been getting this error. Any help would be greatly appreciated.

[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (default) @ jpmml-evaluator ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JPMML-Evaluator .................................... FAILURE [  7.174 s]
[INFO] JPMML evaluator code generators .................... SKIPPED
[INFO] JPMML evaluator .................................... SKIPPED
[INFO] JPMML evaluator extensions ......................... SKIPPED
[INFO] JPMML evaluator test harness ....................... SKIPPED
[INFO] JPMML evaluator example applications ............... SKIPPED
[INFO] JPMML KNIME integration tests ...................... SKIPPED
[INFO] JPMML RapidMiner integration tests ................. SKIPPED
[INFO] JPMML R/Rattle integration tests ................... SKIPPED
[INFO] JPMML SAS integration tests ........................ SKIPPED
[INFO] JPMML evaluator code coverage ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.197 s
[INFO] Finished at: 2017-10-13T10:50:04-04:00
[INFO] Final Memory: 12M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (default) on project jpmml-evaluator: Execution default of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.4.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/L1/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.jar
[ERROR] urls[1] = file:/C:/Users/L1/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[2] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[3] = file:/C:/Users/L1/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[4] = file:/C:/Users/L1/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[5] = file:/C:/Users/L1/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[6] = file:/C:/Users/L1/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[7] = file:/C:/Users/L1/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[8] = file:/C:/Users/L1/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[9] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[10] = file:/C:/Users/L1/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[11] = file:/C:/Users/L1/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[12] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[13] = file:/C:/Users/L1/.m2/repository/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
[ERROR] urls[14] = file:/C:/Users/L1/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
[ERROR] urls[15] = file:/C:/Users/L1/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar
[ERROR] urls[16] = file:/C:/Users/L1/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[17] = file:/C:/Users/L1/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar
[ERROR] urls[18] = file:/C:/Users/L1/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[19] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[20] = file:/C:/Users/L1/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[21] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-6/plexus-i18n-1.0-beta-6.jar
[ERROR] urls[22] = file:/C:/Users/L1/.m2/repository/org/apache/maven/plugin-testing/maven-plugin-testing-harness/1.3/maven-plugin-testing-harness-1.3.jar
[ERROR] urls[23] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.jar
[ERROR] urls[24] = file:/C:/Users/L1/.m2/repository/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
[ERROR] urls[25] = file:/C:/Users/L1/.m2/repository/junit/junit/4.11/junit-4.11.jar
[ERROR] urls[26] = file:/C:/Users/L1/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by vruusmann** [comment] 2019-01-08 21:16
There shouldn't be any practical reason to build the JPMML-Evaluator project from source checkout anymore.

If one is looking for the library JAR files, then they are available via the Maven Central repository. If one is looking for the executable uber-JAR files (eg. to play with example command-line applications), then they are available from GitHub releases page:
https://github.com/jpmml/jpmml-evaluator/releases

Apache Maven is awesome. I have absolutely no interest to waste my time supporting legacy and/or alternative build systems (eg. Apache Ant, Gradle, SBT).

**Closed by vruusmann** 2019-01-08 21:16 UTC

**Comment by kwei94** [comment] 2019-08-11 11:28
Hi vruusmann, 

i had created my project and follow the step as the link below:
1.install maven using mvn archetype:generate -DarchetypeGroupId=de.learnlib.archetypes -DarchetypeArtifactId=complete
pom.xml is created after step1.

2.Then,I follow the step as the link below,but i cannot found .ser file in target file of maven project..
https://stackoverflow.com/questions/50399674/how-to-use-jpmml-android-to-implement-a-pmml-machine-learning-model/50464829

May i know what is my problem?  

![maven](https://user-images.githubusercontent.com/53994150/62833219-c7241a80-bc6d-11e9-845c-d4d73243ffef.PNG)
