### ISSUE TITLE
PMML file missing model element

### ISSUE THREAD

**Issue by SunGoodIn** [jpmml/jpmml-evaluator#194] opened 2020-06-18 09:00 UTC
Hi author,
this is my PMML file(has TransformationDictionary, no Model)
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_3" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.3">
	<Header>
		<Application name="JPMML-SkLearn" version="1.5.29"/>
		<Timestamp>2020-06-16T10:17:57Z</Timestamp>
	</Header>
	<MiningBuildTask>
		<Extension>PMMLPipeline(steps=[('09_MinMaxScaler', DataFrameMapper(default=False, df_out=True,
        features=[(['previous', 'duration', 'balance', 'campaign', 'day', 'age', 'pdays'], MinMaxScaler(copy=True, feature_range=(0, 1)), {})],
        input_df=True, sparse=False))])</Extension>
	</MiningBuildTask>
	<DataDictionary>
		<DataField name="previous" optype="continuous" dataType="double"/>
		<DataField name="duration" optype="continuous" dataType="double"/>
		<DataField name="balance" optype="continuous" dataType="double"/>
		<DataField name="campaign" optype="continuous" dataType="double"/>
		<DataField name="day" optype="continuous" dataType="double"/>
		<DataField name="age" optype="continuous" dataType="double"/>
		<DataField name="pdays" optype="continuous" dataType="double"/>
	</DataDictionary>
	<TransformationDictionary>
		<DerivedField name="mix_max_scaler(previous)" optype="continuous" dataType="double">
			<Apply function="*">
				<FieldRef field="previous"/>
				<Constant dataType="double">0.5</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(duration)" optype="continuous" dataType="double">
			<Apply function="*">
				<FieldRef field="duration"/>
				<Constant dataType="double">0.3333333333333333</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(balance)" optype="continuous" dataType="double">
			<Apply function="+">
				<Apply function="*">
					<FieldRef field="balance"/>
					<Constant dataType="double">5.6427039837490125E-5</Constant>
				</Apply>
				<Constant dataType="double">0.047906556822029114</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(campaign)" optype="continuous" dataType="double">
			<Apply function="+">
				<Apply function="*">
					<FieldRef field="campaign"/>
					<Constant dataType="double">0.058823529411764705</Constant>
				</Apply>
				<Constant dataType="double">-0.058823529411764705</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(day)" optype="continuous" dataType="double">
			<Apply function="+">
				<Apply function="*">
					<FieldRef field="day"/>
					<Constant dataType="double">0.034482758620689655</Constant>
				</Apply>
				<Constant dataType="double">-0.034482758620689655</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(age)" optype="continuous" dataType="double">
			<Apply function="*">
				<FieldRef field="age"/>
				<Constant dataType="double">0.01282051282051282</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="mix_max_scaler(pdays)" optype="continuous" dataType="double">
			<Apply function="+">
				<Apply function="*">
					<FieldRef field="pdays"/>
					<Constant dataType="double">0.0021691973969631237</Constant>
				</Apply>
				<Constant dataType="double">0.0021691973969631237</Constant>
			</Apply>
		</DerivedField>
	</TransformationDictionary>
</PMML>
```
- 1.Is a PMMl file available without Model element
- 2.If the file is available，how to use the PMML file for data preprocessing?(pmml-evaluator)
What is the API?

thinks

**Comment by vruusmann** [comment] 2020-06-18 09:04
Closing as an exact duplicate of https://github.com/jpmml/jpmml-evaluator/issues/96

**Closed by vruusmann** 2020-06-18 09:04 UTC
