### ISSUE TITLE
troubles with org.jpmml.evaluator.InvalidResultException

### ISSUE THREAD

**Issue by luckaB** [jpmml/jpmml-evaluator#75] opened 2017-09-13 14:56 UTC
Hi!

I have implemented a simple application for document classification based on your tutorial. The model is trained in Python and saved to pmml using sklearn2pmml. It worked perfectly before I changed the way I prepare features for the classification (now I use doc2vec implented by DL4J, but I guess that is not important). My code now fails during the preparation of arguments for evaluation:

```           //prepare arguments for scoring
            Map<FieldName, FieldValue> arguments = new LinkedHashMap<>();
            List<InputField> inputFields = evaluator.getInputFields();
            for(InputField inputField : inputFields){
                FieldName inputFieldName = inputField.getName();

                // The raw (ie. user-supplied) value could be any Java primitive value
                Object rawValue = docFeaturesMap.get(inputFieldName.getValue());

                if (rawValue == null) {
                    rawValue = 0.0;
                }

                // The raw value is passed through: 1) outlier treatment, 2) missing value treatment, 3) invalid
                // value treatment and 4) type conversion
                FieldValue inputFieldValue = inputField.prepare(rawValue);

                arguments.put(inputFieldName, inputFieldValue);
            }
```

I get the exception `org.jpmml.evaluator.InvalidResultException (at or around line 441)` at this line:
`FieldValue inputFieldValue = inputField.prepare(rawValue);`
and I cannot figure out why. The `rawValue` is loaded correctly, its value is 0.003755918238312006.

Can you give me some hint on what I'm doing wrong?

**Comment by vruusmann** [comment] 2017-09-13 16:00
> I get the exception org.jpmml.evaluator.InvalidResultException (at or around line 441) at this line
> FieldValue inputFieldValue = inputField.prepare(rawValue);

The model thinks that the value of `rawValue` variable is not a valid input, because it violates some validation criterion. For example, it could be that the valid input range is defined as `[-1, 0]`, and you're trying to pass `0.00375` there.

If you showed me the top three lines of the exception stack trace, then I could suggest what this validation criterion is.

Open your PMML document in text editor, and scroll to line 441. What do you see?

**Comment by luckaB** [comment] 2017-09-14 08:15
In the PMML document I have the following:
```
<MiningSchema>
	<MiningField name="y" usageType="target"/>
	<MiningField name="doc2vecFeature_12" missingValueTreatment="asIs"/>
	<MiningField name="Line_area_average" missingValueTreatment="asIs"/>
	<MiningField name="Par_length_max" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_58" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_38" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_72" missingValueTreatment="asIs"/>
	<MiningField name="Formatting_bold_rel_length_average" missingValueTreatment="asIs"/>
	<MiningField name="Line_rel_length_average" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_99" missingValueTreatment="asIs"/>
	<MiningField name="Block_rel_width_max" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_92" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_23" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_97" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_68" missingValueTreatment="asIs"/>
	<MiningField name="Block_area_max" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_10" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_5" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_80" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_76" missingValueTreatment="asIs"/>
	<MiningField name="Line_area_max" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_48" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_41" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_74" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_22" missingValueTreatment="asIs"/>
	<MiningField name="Line_height_min" missingValueTreatment="asIs"/>
	<MiningField name="doc2vecFeature_51" missingValueTreatment="asIs"/>
	<MiningField name="Line_area_min" missingValueTreatment="asIs"/>
</MiningSchema>
```

The line 441 is this one: `<MiningField name="doc2vecFeature_38" missingValueTreatment="asIs"/>` which makes sense, since it is the feature at which my code fails.

These are the top lines of the exception stack trace:
```
org.jpmml.evaluator.InvalidResultException (at or around line 441)
	at org.jpmml.evaluator.FieldValueUtil.performInvalidValueTreatment(FieldValueUtil.java:178)
	at org.jpmml.evaluator.FieldValueUtil.prepareInputValue(FieldValueUtil.java:90)
	at org.jpmml.evaluator.InputField.prepare(InputField.java:64)
```

The thing that I don't understand is that I would expect all of the doc2vec features to be from the same range (I guess it is [-1,1]). When I tried to debug the code the iteration went trough the features in the order as it is defined in the PMML document. Thus there were two doc2vec features succesfully loaded and processed before the one that the code fails on. These features and their values are:
`doc2vecFeature_12 = -0.0329` and `doc2vecFeature_58 = 0.023832`
I can't really see how is the feature `doc2vecFeature_38` and its value and/or its validation criterion different from the previous two.

**Comment by vruusmann** [comment] 2017-09-14 08:32
> `<MiningField name="doc2vecFeature_38" missingValueTreatment="asIs"/>`

The `MiningField` element also has several other attributes:
http://dmg.org/pmml/v4-3/MiningSchema.html

The one that is causing problems here is the `MiningField@invalidValueTreatment` attribute, which has a default value `returnInvalid`. The JPMML-Evaluator library sees that the input value for the `doc2vecFeature_38` field is invalid, and raises an `org.jpmml.evaluator.InvalidResultException` as ordered to do by the `MiningField@invalidValueTreatment="returnInvalid"` attribute.

The definitions of fields are actually given by `DataDictionary/DataField` elements. How does the `DataField` element look for the `doc2vecFeature_38` field? I suspect it has an `Interval` child element, which restricts the numeric value to a specific range, which `0.0037559` violates.

In the latter case, the solution would be to "expand" all `Interval` elements to the desired range. For example, if the theory suggests that all Doc2Vec values must be in `[-1, 1]` range, then simply replace existing `Interval` elements with `<Interval leftMargin="-1" rightMargin="1"/>` elements. You can use the JPMML-Model library to easily modify existing PMML documents.

**Comment by luckaB** [comment] 2017-09-14 09:16
Yes, you are right, the `DataField` element specifies an interval and my value lies out of it.
```
<DataField name="doc2vecFeature_38" optype="continuous" dataType="double">
	<Interval closure="closedClosed" leftMargin="0.02565521001815796" rightMargin="0.2292778342962265"/>
</DataField>
```

Thank you very much! :)

One last question (hopefully):  When and how are the intervals set? Why does the model think that this specific feature shouldn't have lower value than 0.02565521001815796 and higher than 0.2292778342962265? Are these numbers the minimum and maximum that was found in the training set?

**Comment by vruusmann** [comment] 2017-09-14 09:32
> Are these numbers the minimum and maximum that was found in the training set?

Exactly. The intervals are based on training data, and they are supposed to represent the intended "applicability domain" of the model. The thinking goes that if your training data did not contain negative values, then the model is probably not ready to handle them, and shouldn't be applied to negative testing data.

In that sense, getting a `org.jpmml.evaluator.InvalidResultException` is a feature, not a bug, because it potentially saved your application from making a non-sensical prediction. But as explained above, if you feel that this safeguard is not needed, then you may manually override the default "applicability domain" with a custom one.

Check the configuration options of your PMML producer software - it may be possible to disable the generation of `Interval` elements.

Closing this issue, as the JPMML-Evaluator library is apparently OK as it is.

**Closed by vruusmann** 2017-09-14 09:32 UTC
