### ISSUE TITLE
API to validate a pmml in jpmml

### ISSUE THREAD

**Issue by kaushalkumar** [jpmml/jpmml-evaluator#225] opened 2021-06-14 04:37 UTC
Hi - We are looking for an API to validate if the pmml is valid, such that it does not fails due to model being invalid during execution. Can you please point me to that.

I was assuming that if evaluator object is constructed and verified successfully (with any exception), then it means that pmml is valid; but it seems that this is not the case, since we found a scenario where pmml was loaded successfully, but error came during evaluation. The error was due to missing datatype in DataField tag.

**Comment by vruusmann** [comment] 2021-06-14 17:00
Closing as exact duplicate of https://github.com/jpmml/jpmml-model/issues/29

**Closed by vruusmann** 2021-06-14 17:00 UTC

**Comment by kaushalkumar** [comment] 2021-06-15 05:21
Hi @vruusmann - thanks for closing this. I created it by mistake, sorry about it.
