### ISSUE TITLE
Random Forest Some Segments are null causing TypeCheckException

### ISSUE THREAD

**Issue by rajpalparyani** [jpmml/jpmml-evaluator#65] opened 2017-07-18 02:46 UTC
Hi,

I am using "jpmml-sparkml, version 1.2.4" to generate Random Forest PMML models in spark (using Scala) and saving that output to local file system. I am then using "jpmml-evaluator , version 1.3.7" 

While scoring the models , for some inputs I am getting the following exception
```
org.jpmml.evaluator.TypeCheckException: Expected org.jpmml.evaluator.HasProbability, but got null
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:485)
	at org.jpmml.evaluator.mining.SegmentResult.getTargetValue(SegmentResult.java:92)
	at org.jpmml.evaluator.mining.MiningModelUtil.aggregateProbabilities(MiningModelUtil.java:169)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateClassification(MiningModelEvaluator.java:302)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:220)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:186)
	at EvaluatePredictive.getPredictions(EvaluatePredictive.java:133)
	at EvaluatePredictive.getAll(EvaluatePredictive.java:71)
	at EvaluatePredictive.main(EvaluatePredictive.java:32)
```
I debugged the code and found out that for some values of input , we get null segments and as a result above exception is thrown.

I have been searching online through different sources , but still haven't got a solution to this .. 

Can you please help .. I would be grateful for any directions.

Looking forward to your response.

Thanks,
Raj

**Comment by vruusmann** [comment] 2017-07-18 07:19
Duplicate of https://github.com/jpmml/jpmml-evaluator/issues/54

> I debugged the code and found out that for some values of input, we get null segments and as a result above exception is thrown.

Apparently, you're invoking `Evaluator#evaluate(Map)` with an incomplete map of arguments.

**Closed by vruusmann** 2017-07-18 07:19 UTC

**Comment by rajpalparyani** [comment] 2017-07-18 20:47
@vruusmann  - The arguments are passed as valid values (not incomplete) to the to the Evaluator#evaluate(Map) function .

For some values ,we see the above exception , but other values are scored successfully. 

For the values that are failing , we see the null segments. Those contain some sensitive information , and I would prefer a private chat for discussing that. Please let me know if there's a way we can discuss this interactively (on skype or some other chat).

Thanks a lot for the help .. Really appreciate it :)

Thanks,
Raj

**Comment by vruusmann** [comment] 2017-07-18 20:58
@rajpalparyani My e-mail is given in my GitHub profile.

What is needed for troubleshooting the problem:

- A PMML file.
- A CSV file that contains at least one "successful" data record and one "failing" data record.
- Excerpt from your Java application showing how you query the list of input fields (do you do `Evaluator#getInputFields()` or `Evaluator#getActiveFields()`), how you prepare their values, and how you perform the evaluation - should be around 15 to 20 lines of Java code max.

Can you reproduce the error condition using some public dataset, such as the Iris dataset?
