### ISSUE TITLE
Missed resources

### ISSUE THREAD

**Issue by MacleZhou** [jpmml/jpmml-evaluator#182] opened 2020-01-26 01:42 UTC
In class ReportingValueFactoryFactory, which referenced but not able to find below files:

ReportingFloatValue, ReportingComplexFloatVector, ReportingSimpleFloatVector, ReportingDoubleValue, ReportingComplexDoubleVector, ReportingSimpleDoubleVector. 

Please help.

**Comment by vruusmann** [comment] 2020-01-26 07:59
Exact duplicate of https://github.com/jpmml/jpmml-evaluator/issues/162

**Closed by vruusmann** 2020-01-26 07:59 UTC
