### ISSUE TITLE
jakarta.xml.bind.JAXBException

### ISSUE THREAD

**Issue by zhang0557kui** [jpmml/jpmml-evaluator#235] opened 2021-12-22 08:39 UTC
when I use:
```java
Evaluator model = new LoadingModelEvaluatorBuilder()
  .load(new File("clf.pmml"))
  .build();
```
and jakarta.xml.bind.JAXBException occured.
somebody know the reason?

**Comment by vruusmann** [comment] 2021-12-22 17:23
Closing as an exact duplicate of #234

**Closed by vruusmann** 2021-12-22 17:23 UTC
